const database = {
  sentences: [
    {
      sentence: "She always eats breakfast before school.",
      correctOrder: ["She", "always", "eats", "breakfast", "before", "school"],
      audioFilePath: "./mp3/000.mp3",
    },
    {
      sentence: "They often go to the park on Sundays.",
      correctOrder: [
        "They",
        "often",
        "go",
        "to",
        "the",
        "park",
        "on",
        "Sundays",
      ],
      audioFilePath: "./mp3/001.mp3",
    },
    {
      sentence: "I sometimes play soccer in the afternoon.",
      correctOrder: [
        "I",
        "sometimes",
        "play",
        "soccer",
        "in",
        "the",
        "afternoon",
      ],
      audioFilePath: "./mp3/002.mp3",
    },
    {
      sentence: "He rarely watches TV in the morning.",
      correctOrder: ["He", "rarely", "watches", "TV", "in", "the", "morning"],
      audioFilePath: "./mp3/003.mp3",
    },
    {
      sentence: "She usually reads books before bedtime.",
      correctOrder: ["She", "usually", "reads", "books", "before", "bedtime"],
      audioFilePath: "./mp3/004.mp3",
    },
    {
      sentence: "We always finish our homework after dinner.",
      correctOrder: [
        "We",
        "always",
        "finish",
        "our",
        "homework",
        "after",
        "dinner",
      ],
      audioFilePath: "./mp3/005.mp3",
    },
    {
      sentence: "He hardly ever drinks coffee in the evening.",
      correctOrder: [
        "He",
        "hardly",
        "ever",
        "drinks",
        "coffee",
        "in",
        "the",
        "evening",
      ],
      audioFilePath: "./mp3/006.mp3",
    },
    {
      sentence: "They never forget to call their parents on weekends.",
      correctOrder: [
        "They",
        "never",
        "forget",
        "to",
        "call",
        "their",
        "parents",
        "on",
        "weekends",
      ],
      audioFilePath: "./mp3/007.mp3",
    },
    {
      sentence: "She usually goes to bed early on weekdays.",
      correctOrder: [
        "She",
        "usually",
        "goes",
        "to",
        "bed",
        "early",
        "on",
        "weekdays",
      ],
      audioFilePath: "./mp3/008.mp3",
    },
    {
      sentence: "I sometimes visit my grandparents on holidays.",
      correctOrder: [
        "I",
        "sometimes",
        "visit",
        "my",
        "grandparents",
        "on",
        "holidays",
      ],
      audioFilePath: "./mp3/009.mp3",
    },
    {
      sentence: "He always helps his sister with her homework after school.",
      correctOrder: [
        "He",
        "always",
        "helps",
        "his",
        "sister",
        "with",
        "her",
        "homework",
        "after",
        "school",
      ],
      audioFilePath: "./mp3/010.mp3",
    },
    {
      sentence: "We often go swimming in the river on hot days.",
      correctOrder: [
        "We",
        "often",
        "go",
        "swimming",
        "in",
        "the",
        "river",
        "on",
        "hot",
        "days",
      ],
      audioFilePath: "./mp3/011.mp3",
    },
    {
      sentence: "She rarely goes out at night.",
      correctOrder: ["She", "rarely", "goes", "out", "at", "night"],
      audioFilePath: "./mp3/012.mp3",
    },
    {
      sentence: "They sometimes eat lunch in the cafeteria.",
      correctOrder: [
        "They",
        "sometimes",
        "eat",
        "lunch",
        "in",
        "the",
        "cafeteria",
      ],
      audioFilePath: "./mp3/013.mp3",
    },
    {
      sentence: "He usually finishes work late.",
      correctOrder: ["He", "usually", "finishes", "work", "late"],
      audioFilePath: "./mp3/014.mp3",
    },
    {
      sentence: "She often listens to music in the evening.",
      correctOrder: [
        "She",
        "often",
        "listens",
        "to",
        "music",
        "in",
        "the",
        "evening",
      ],
      audioFilePath: "./mp3/015.mp3",
    },
    {
      sentence: "I rarely play video games on weekdays.",
      correctOrder: ["I", "rarely", "play", "video", "games", "on", "weekdays"],
      audioFilePath: "./mp3/016.mp3",
    },
    {
      sentence: "He always walks his dog in the morning.",
      correctOrder: [
        "He",
        "always",
        "walks",
        "his",
        "dog",
        "in",
        "the",
        "morning",
      ],
      audioFilePath: "./mp3/017.mp3",
    },
    {
      sentence: "She sometimes goes shopping with her friends on Saturdays.",
      correctOrder: [
        "She",
        "sometimes",
        "goes",
        "shopping",
        "with",
        "her",
        "friends",
        "on",
        "Saturdays",
      ],
      audioFilePath: "./mp3/018.mp3",
    },
    {
      sentence: "They often have dinner at a restaurant on special occasions.",
      correctOrder: [
        "They",
        "often",
        "have",
        "dinner",
        "at",
        "a",
        "restaurant",
        "on",
        "special",
        "occasions",
      ],
      audioFilePath: "./mp3/019.mp3",
    },
  ],
};
